// Mocks generated by Mockito 5.3.2 from annotations
// in todoapp/test/features/todo/domain/usecases/get_todo_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todoapp/features/todo/domain/entities/todo.dart' as _i4;
import 'package:todoapp/features/todo/domain/repositories/todo_repository.dart'
    as _i3;
import 'package:todoapp/features/todo/domain/usecases/add_todo.dart' as _i6;
import 'package:todoapp/features/todo/domain/usecases/check_todo.dart' as _i7;
import 'package:todoapp/features/todo/domain/usecases/remove_todo_by_id.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i3.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Either<Exception, List<_i4.Todo>> getTodoList() => (super.noSuchMethod(
        Invocation.method(
          #getTodoList,
          [],
        ),
        returnValue: _FakeEither_0<Exception, List<_i4.Todo>>(
          this,
          Invocation.method(
            #getTodoList,
            [],
          ),
        ),
      ) as _i2.Either<Exception, List<_i4.Todo>>);
  @override
  _i5.Future<_i2.Either<Exception, bool>> addTodo(_i6.AddTodoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [params],
        ),
        returnValue: _i5.Future<_i2.Either<Exception, bool>>.value(
            _FakeEither_0<Exception, bool>(
          this,
          Invocation.method(
            #addTodo,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Either<Exception, bool>>);
  @override
  _i5.Future<_i2.Either<Exception, bool>> checkTodo(
          _i7.CheckTodoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkTodo,
          [params],
        ),
        returnValue: _i5.Future<_i2.Either<Exception, bool>>.value(
            _FakeEither_0<Exception, bool>(
          this,
          Invocation.method(
            #checkTodo,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Either<Exception, bool>>);
  @override
  _i5.Future<_i2.Either<Exception, bool>> removeTodoByid(
          _i8.RemoveTodoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTodoByid,
          [params],
        ),
        returnValue: _i5.Future<_i2.Either<Exception, bool>>.value(
            _FakeEither_0<Exception, bool>(
          this,
          Invocation.method(
            #removeTodoByid,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Either<Exception, bool>>);
}
